spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mp_high?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456

logging:
  level:
    root: warn
    com.example: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  global-config:
    db-config:
      # 可以在字段上加上@TableLogic
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)